# -*- coding: utf-8 -*-
"""Word2Vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgZaGk8fGYoKA1aOAkk9k49Kikns1j1X

<b>problem with bag or words and tf-idf</b>
</br> In both of the above mentioned approaches these will not maintain semantic information</br>
like the  relationship between two words based on the context 
For example:
While performing bag of words we assign each word as a single dimension,</br>
so man,women and apple each get different dimension but we know that man and women are more related and apple is different from those</br>
so if we have a system which can actually idetify this kind of </br>
relationship it would produce better results</br>
<b>Solution:Word2Vec</br></b>
Each word is represented as a vector rather than single number</br>
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
#module for word2vec conversion
from gensim.models import Word2Vec
from nltk.corpus import stopwords

import re

paragraph='''I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career'''

#preprocessing data
text=re.sub(r'\[[0-9]*\]',' ',paragraph)
text=re.sub(r'\s+',' ',text)
text=text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)
print(text)

# Preparing the dataset
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]
for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

#Training the Word2Vec model
model = Word2Vec(sentences, min_count=1)

#generate the word vector
words = model.wv.vocab
vector = model.wv['war']
# Most similar words
similar = model.wv.most_similar('war')

print(vector)
'''
[ 9.75956384e-04 -3.27145169e-03  2.55480735e-03 -2.59914610e-04
  2.46611866e-03  4.46372665e-03  6.74074341e-04 -4.81954450e-03
 -3.50633590e-03  4.47917497e-03 -3.85374133e-03  6.67996821e-04
  1.60799958e-04  1.56731578e-03  4.70787380e-03 -3.37290531e-03
 -2.47605052e-03  4.04259562e-03 -1.26232207e-03  5.36568521e-04
  3.19323828e-03 -1.51189452e-03 -4.26065316e-03  2.55130534e-03
  9.76914816e-05  1.39511062e-03  4.97107022e-03  3.25843063e-03
  1.07691088e-03 -3.47809470e-03  4.01597982e-03 -1.79142680e-03
 -2.89048709e-04 -8.29033146e-04  3.08835600e-03  1.58434108e-04
 -1.64068028e-04  1.83006795e-03  2.29358580e-03  4.72600199e-03
  1.17061974e-03 -2.01519555e-03  3.43630766e-03 -1.41626212e-03
 -1.49303407e-03 -3.47067835e-03 -3.58310668e-03  4.81548905e-03
  2.06227088e-03 -2.08623265e-03 -2.00848887e-03 -1.12224719e-03
  1.14334136e-04 -1.72966428e-03 -1.25680002e-03  3.49823764e-04
 -4.12784610e-03  2.15417822e-03 -4.05060331e-04  3.65859549e-03
  1.98360230e-03  1.36897981e-03 -3.34074651e-03 -1.29008014e-03
 -2.55630328e-03  1.53429795e-03  2.82927509e-03 -3.40386503e-03
  1.59879343e-03 -3.46688996e-03  2.63103843e-03 -3.58892395e-03
  2.77307630e-03  4.29483689e-03 -6.56623277e-04  4.45496431e-03
  1.60766323e-03  1.18526269e-03  2.01055524e-03  4.50584991e-03
  1.61600695e-03 -2.09402037e-03 -3.80057935e-03 -3.00534093e-03
 -7.66789948e-04  1.56707410e-03 -1.73756829e-03  3.33328126e-03
  2.94216257e-03  2.47601233e-03 -4.53975797e-03 -9.18831211e-05
  2.64537078e-03 -7.89741171e-04  5.31800615e-04  2.59749172e-03
  1.49614795e-03 -7.32719840e-04  4.25207254e-04 -2.71206233e-03]
'''

print(similar)
'''[('come', 0.26128891110420227), ('looted', 0.26108604669570923), 
('economic', 0.24544432759284973), ('globally', 0.20753997564315796), 
('falling', 0.1803778111934662), ('development', 0.17647512257099152), 
('done', 0.16133928298950195), ('grabbed', 0.16057735681533813), 
('respect', 0.15594890713691711), ('space', 0.15556937456130981)]'''